language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - mkdir -p build/logs
  - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "doctrine/orm:${DOCTRINE_VERSION}" --no-update; fi;

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: DOCTRINE_VERSION=2.4.*
    - php: 7.0
      env: DOCTRINE_VERSION=2.5.*

install: composer update --prefer-dist $COMPOSER_FLAGS

after_script:
  - travis_retry php vendor/bin/coveralls -v
