language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - mkdir -p build/logs
  - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "symfony/symfony:${DOCTRINE_VERSION}" --no-update; fi;

matrix:
  include:
#    - php: 5.5
#      env: COMPOSER_FLAGS="--prefer-lowest"
#    - php: 5.5
#      env: DOCTRINE_VERSION=2.3.*
#    - php: 5.5
#      env: DOCTRINE_VERSION=2.4.*
    - php: 5.5
      env: DOCTRINE_VERSION=2.5.*
  allow_failures:
    - php: hhvm

install: composer update --prefer-dist $COMPOSER_FLAGS

after_script:
  - travis_retry php vendor/bin/coveralls -v
