# Setup
title:        Doctrine-Filter
tagline:      A library to help filter Doctrine entities.
baseurl:      ""

# About/contact
author:
  name:       bitecodes
  url:        http://bite.codes

#Others
markdown: kramdown